import { Logo } from './svgs'
import {
  IconTemperature,
  IconWifi,
  IconLock,
  IconTools,
  IconDroplet,
  IconWall,
  IconPaint,
  IconBrush,
  IconBolt,
  IconPlug,
  IconAlarm,
  IconCamera,
  IconTank,
  IconShield,
  IconClock,
  IconCertificate,
  IconUser,
  IconDoor,
  IconBuildingCastle,
  IconBulb,
  IconAlarmSmoke,
  IconCampfire,
  IconTimeline,
  IconBucketOff,
  IconVector,
  IconDroplets,
  IconDropletOff,
  IconCylinder,
  IconThermometer,
  IconRecycle,
  IconTool,
  IconRefresh,
  IconCloudRain,
  IconFence,
  IconToolsKitchen3,
  IconBrandFacebook,
  IconBrandTwitter,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconMail,
  IconPhone,
  IconBrandYoutube,
  IconBrandPinterest,
  IconBrandTiktok,
  IconStar,
  IconInfoCircle,
  IconSettings,
  IconCircleCheck,
  IconMapPin,
  IconCircuitResistor,
  IconCurrencyLira,
  IconMoodHappy,
  IconAdjustments,
  IconDeviceLaptop,
  IconAirConditioning,
  IconMeterSquare,
  IconSwitch,
  IconEngine,
  IconRoute,
  IconPlugConnected,
  IconCircuitCell,
  IconCircuitSwitchClosed,
  IconSnowflake,
  IconFlame,
  IconGauge,
  IconBox,
  IconFilter,
  IconScale,
  IconRobot,
  IconDeviceDesktop,
  IconBottle,
  IconRuler,
  IconSearch,
  IconPool,
  IconBuilding,
  IconWash,
  IconTestPipe,
  IconCircuitAmmeter,
  IconDeviceAnalytics,
  IconArrowBearRight,
  IconAsset,
  IconAssembly,
  IconTemperatureSun,
  IconAnalyze,
  IconBath,
  IconToiletPaper,
  IconBiohazard,
  IconGizmo,
  IconEscalator,
  IconTrowel,
  IconSettingsCog,
  IconUvIndex,
  IconHome,
} from '@tabler/icons-react'

export const icons = {
  logo: Logo,
  'isitma-ve-sogutma': IconTemperature,
  'elektrik-tesisat': IconBolt,
  'sihhi-tesisat': IconDroplet,
  'elektronik-tesisat': IconCircuitResistor,
  'havuz-sistemleri': IconPool,
  'cati-ve-cephe': IconHome,
  'yapi-insaati': IconBuilding,
  internet: IconWifi,
  guvenlik: IconLock,
  bakim: IconTools,
  boyama: IconPaint,
  'asma-tavan-sistemleri': IconBuildingCastle,
  'alci-duvar-uygulamalari': IconWall,
  'ytong-tugla-duvar': IconWall,
  'alci-isleri': IconPaint,
  'ic-mekan-boyama': IconBrush,
  'kablo-yenileme': IconPlug,
  'karbon-monoksit-dedektorleri': IconAlarmSmoke,
  'dogal-gaz-kacak-alarm-dedektorleri': IconAlarm,
  'yangin-alarm-sistemleri': IconAlarm,
  'interkom-sistemleri': IconAlarm,
  'guvenlik-kamerasi-sistemleri': IconCamera,
  'zemin-isitma-sistemi-montaji': IconCampfire,
  'pprc-boru-montajlari': IconTimeline,
  'su-kacagi-tespiti': IconBucketOff,
  'kollektor-montaji': IconVector,
  'hidrofor-sistemleri': IconTank,
  'su-deposu-bakimi': IconTank,
  'su-sayaci-montaji': IconDroplets,
  'musluk-ve-krano-montajlari': IconDroplet,
  'atik-su-drenaj-sistemleri': IconDropletOff,
  'yeni-nesil-esnek-dogal-gaz-borulama': IconCylinder,
  'kombinin-bakim-ve-onarimi': IconThermometer,
  'iki-yonlu-kimyasal-radyator-temizligi': IconRecycle,
  'klima-montaji-ve-sokumu': IconTool,
  'bordur-yenileme': IconRefresh,
  'yagmur-suyu-drenaj-kanallari': IconCloudRain,
  'cephe-kaplama': IconShield,
  'isi-yalitim-sistemleri': IconShield,
  'terasta-su-yalitimi': IconShield,
  'havuz-yalitimi': IconShield,
  'bahce-calismalari': IconFence,
  'memnuniyet-garantisi': IconMoodHappy,
  'kapi-ve-pencere-onarimlari': IconDoor,
  'mutfak-yenilemeleri': IconToolsKitchen3,
  'mutfak-dolabi-montaji': IconTool,
  'tezgah-yenileme': IconRefresh,
  'elektrik-ariza-onarimi': IconBolt,
  'dimmer-anahtar-montaji': IconAdjustments,
  'spot-montaji': IconBulb,
  'led-aydinlatma-sistemleri': IconBulb,
  'elektrik-sayaci-montaji': IconMeterSquare,
  'salter-montaj-ve-degisimi': IconSwitch,
  'jenerator-baglantisi': IconEngine,
  'zayif-akim-tesisati': IconCircuitAmmeter,
  'kablo-kanali-doseme': IconRoute,
  'topraklama-hatti-cekimi': IconPlugConnected,
  'elektrik-tesisati-yenileme': IconCircuitCell,
  'kacak-akim-rolesi-montaji': IconCircuitSwitchClosed,
  'aydinlatma-tesisati': IconBulb,
  'sensor-montaji': IconDeviceAnalytics,
  'avize-montaji': IconBulb,
  'priz-ve-anahtar-degisimi': IconPlug,
  'sigorta-kutusu-yenileme': IconBox,
  'tesisat-kablolari-yenileme': IconArrowBearRight,
  'elektrik-panosu-yenileme': IconDeviceDesktop,
  'elektrik-ariza-tespiti': IconSearch,
  'tesisat-izolasyonu': IconShield,
  'sicak-su-sistemi-kurulumu': IconTemperature,
  'otomasyon-sistemi-kurulumu': IconDeviceLaptop,
  'gaz-kacagi-tespiti-ve-onarimi': IconGauge,
  'isi-istasyonu-kurulum-ve-bakimi': IconTemperature,
  'kalorifer-tesisati-yenileme': IconAirConditioning,
  'isi-pompasi-montaj-ve-bakimi': IconAsset,
  'brulor-bakim-ve-tamiri': IconFlame,
  'havalandirma-sistemi-kurulumu': IconAirConditioning,
  'fancoil-sistem-montaj-ve-bakimi': IconAirConditioning,
  'vrf-vrv-sistem-kurulumu': IconAirConditioning,
  'termostatik-vana-montaji': IconAssembly,
  'radyator-montaj-ve-degisimi': IconTemperatureSun,
  'dogalgaz-tesisat-doseme-ve-bakimi': IconFlame,
  'kazan-dairesi-bakim-ve-onarimi': IconEngine,
  'yerden-isitma-sistem-kurulumu': IconTemperature,
  'cift-yonlu-ilacli-petek-temizligi': IconWash,
  'klima-montaj-sokum-ve-bakimi': IconAirConditioning,
  'kombi-montaj-tamir-ve-bakimi': IconFlame,
  'merkezi-kalorifer-sistemi-kurulumu-ve-bakimi': IconBuilding,
  'basinc-testi-ve-kontrol': IconGauge,
  'termal-kamera-ile-kacak-tespiti': IconCamera,
  'rogar-ve-kanal-temizligi': IconAnalyze,
  'yagmur-suyu-drenaji': IconDroplet,
  'dusakabin-kurulumu': IconBath,
  'lavabo-ve-klozet-montaji': IconToiletPaper,
  'musluk-ve-batarya-montaji': IconTool,
  'pis-su-tesisati-doseme': IconBiohazard,
  'pompa-sistemleri-kurulumu': IconGizmo,
  'su-deposu-bakim-ve-temizligi': IconWash,
  'pprc-boru-tesisati': IconEscalator,
  'temiz-su-tesisati-doseme': IconDroplet,
  'tesisat-yenileme-ve-tadilat': IconTool,
  'tikaniklik-acma-hizmeti': IconPlug,
  'pis-su-gider-acma': IconBiohazard,
  'su-kacagi-tespiti-ve-tamiri': IconDroplet,
  'drenaj-hatti-ve-kuyusu-yapimi': IconTrowel,
  'su-aritma-ve-yumusatma-sistemleri': IconFilter,
  'su-sayaclari-kollektor-tesisati': IconMeterSquare,
  'hidrofor-tesisati-kurulumu': IconDroplets,
  'jet-sistemi-montaj-ve-tamiri': IconSettingsCog,
  'su-seviye-kontrolu-ve-ayari': IconRuler,
  'havuz-kimyasallari-tedariki': IconBottle,
  'havuz-firca-ve-supurge-sistemleri': IconTool,
  'kis-bakimi-ve-koruma': IconSnowflake,
  'havuz-tesisat-yenileme': IconPool,
  'havuz-motoru-bakim-ve-tamiri': IconEngine,
  'ph-dengeleme-sistemi-kurulumu': IconScale,
  'klor-jeneratoru-montaji': IconEngine,
  'skimmer-ve-suzgec-degisimi': IconFilter,
  'havuz-kaplama-ve-izolasyonu': IconShield,
  'uv-sterilizasyon-sistemi-montaji': IconUvIndex,
  'havuz-robotu-tamiri': IconRobot,
  'havuz-isitma-sistemi-kurulumu': IconTemperature,
  'havuz-aydinlatma-sistemi-montaji': IconBulb,
  'otomatik-dozajlama-sistemi-kurulumu': IconScale,
  'havuz-filtre-sistemi-bakimi': IconFilter,
  'havuz-pompasi-montaj-ve-tamiri': IconPool,
  'havuz-suyu-analizi-ve-ilaclama': IconTestPipe,
  'havuz-bakimi-ve-temizligi': IconPool,
  '7-24-hizmet': IconClock,
  'sertifikali-usta': IconCertificate,
  'profesyonel-uzmanlik': IconUser,
  'seffaf-fiyatlandirma': IconCurrencyLira,
  'iscilik-ve-malzeme-kalitesi': IconCertificate,
  facebook: IconBrandFacebook,
  twitter: IconBrandTwitter,
  instagram: IconBrandInstagram,
  linkedin: IconBrandLinkedin,
  email: IconMail,
  phone: IconPhone,
  address: IconMapPin,
  youtube: IconBrandYoutube,
  pinterest: IconBrandPinterest,
  tiktok: IconBrandTiktok,
  yildiz: IconStar,
  onay: IconCircleCheck,
  bilgi: IconInfoCircle,
  ayarlar: IconSettings,
  sertifika: IconCertificate,
  kullanici: IconUser,
  harita: IconMapPin,
}
