/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    'service-categories': ServiceCategory;
    projects: Project;
    testimonials: Testimonial;
    certifications: Certification;
    posts: Post;
    'post-categories': PostCategory;
    authors: Author;
    'blog-comments': BlogComment;
    proposals: Proposal;
    users: User;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'blog-comments': BlogCommentsSelect<false> | BlogCommentsSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug?: string | null;
  title: string;
  description?: string | null;
  featured_image?: (number | null) | Media;
  blocks?:
    | (
        | {
            blockType: 'home-hero-section';
            /**
             * Add headlines that will rotate in the hero section
             */
            headingRotation?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            subHeading?: string | null;
            description?: string | null;
            /**
             * Select services to display in the rotating list
             */
            featuredServices?: (number | Service)[] | null;
            servicesLink?: {
              text?: string | null;
              url?: string | null;
            };
            images?: {
              /**
               * Recommended: 404x660px
               */
              mainImage?: (number | null) | Media;
              /**
               * Recommended: 269x439px
               */
              secondaryImage?: (number | null) | Media;
            };
            cta_form?: (number | null) | Form;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'services-carousel';
            heading?: {
              subtitle?: string | null;
              title?: string | null;
            };
            viewAllLink?: {
              text?: string | null;
              url?: string | null;
            };
            /**
             * Select services to display in the carousel
             */
            services?: (number | ServiceCategory)[] | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'about-section';
            /**
             * Choose where to load certificates from. "Inline" for manual entry below, "Collection" to automatically fetch from Certifications.
             */
            certificateSource?: ('inline' | 'collection') | null;
            content?: {
              subtitle?: string | null;
              title?: string | null;
              description?: string | null;
              button?: {
                text?: string | null;
                url?: string | null;
              };
            };
            /**
             * Add certificates to display in the carousel (only shown when using "Inline" source)
             */
            certificates?:
              | {
                  title?: string | null;
                  /**
                   * Upload certificate image
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Options for loading certificates from collection
             */
            collectionOptions?: {
              /**
               * Maximum number of certificates to display
               */
              limit?: number | null;
              /**
               * Show only featured certificates
               */
              featuredOnly?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'why-choose-us';
            /**
             * Recommended size: 571x971px
             */
            image?: (number | null) | Media;
            content?: {
              subtitle?: string | null;
              title?: string | null;
              description?: string | null;
            };
            /**
             * Add up to 4 features
             */
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?:
                    | (
                        | '7-24-hizmet'
                        | 'sertifikali-usta'
                        | 'profesyonel-uzmanlik'
                        | 'seffaf-fiyatlandirma'
                        | 'iscilik-ve-malzeme-garantisi'
                        | '25-yillik-tecrube'
                        | 'memnuniyet-garantisi'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'work-process';
            header?: {
              subtitle?: string | null;
              title?: string | null;
            };
            description?: string | null;
            /**
             * Add up to 3 process steps
             */
            processSteps?:
              | {
                  number?: number | null;
                  title?: string | null;
                  /**
                   * Add up to 5 sub-steps
                   */
                  steps?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'portfolio-section';
            header?: {
              subtitle?: string | null;
              title?: string | null;
            };
            description?: string | null;
            /**
             * Select projects to showcase (minimum 2)
             */
            featuredProjects?: (number | Project)[] | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'testimonials-section';
            header?: {
              subtitle?: string | null;
              title?: string | null;
              description?: string | null;
            };
            viewAllButton?: {
              text?: string | null;
              url?: string | null;
            };
            /**
             * Select testimonials to display in this section
             */
            featuredTestimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            blockType: 'blog-section';
            header?: {
              subtitle?: string | null;
              title?: string | null;
            };
            /**
             * Select blog posts to display in this section
             */
            featuredPosts?: (number | Post)[] | null;
            id?: string | null;
            blockName?: string | null;
          }
        | {
            impact?: ('HIGH' | 'MEDIUM' | 'LOW') | null;
            title?: string | null;
            description?: string | null;
            /**
             * Upload an image to be used as the background.
             */
            image?: (number | null) | Media;
            imageAlt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero-block';
          }
        | {
            heading?: string | null;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            values?:
              | {
                  title?: string | null;
                  description?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  icon?:
                    | (
                        | '7-24-hizmet'
                        | 'sertifikali-usta'
                        | 'profesyonel-uzmanlik'
                        | 'seffaf-fiyatlandirma'
                        | 'iscilik-ve-malzeme-garantisi'
                        | '25-yillik-tecrube'
                        | 'memnuniyet-garantisi'
                        | 'email'
                        | 'phone'
                        | 'address'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid-section-block';
          }
        | {
            /**
             * Choose where to load certificates from. "Inline" for manual entry below, "Collection" to automatically fetch from Certifications.
             */
            certificateSource?: ('inline' | 'collection') | null;
            title?: string | null;
            description?: string | null;
            /**
             * Add certificates manually (only shown when using "Inline" source)
             */
            certificates?:
              | {
                  title?: string | null;
                  date?: string | null;
                  /**
                   * Upload an image for the certificate.
                   */
                  image?: (number | null) | Media;
                  description?: string | null;
                  pdfUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Options for loading certificates from collection
             */
            collectionOptions?: {
              /**
               * Maximum number of certificates to display
               */
              limit?: number | null;
              /**
               * Show only featured certificates
               */
              featuredOnly?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'certifications-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            showTitle?: boolean | null;
            showCategories?: boolean | null;
            images?:
              | {
                  src?: (number | null) | Media;
                  category?: (number | null) | ServiceCategory;
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-gallery-block';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            variant?: ('subtle' | 'light' | 'dark' | 'primary') | null;
            faqs?:
              | {
                  question?: string | null;
                  answer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-block';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select projects to display in this section.
             */
            items?: (number | Project)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select testimonials to display in this section.
             */
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials-block';
          }
        | FormBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug?: string | null;
  /**
   * Show this service on location pages
   */
  featured?: boolean | null;
  title?: string | null;
  icon?:
    | (
        | 'asma-tavan-sistemleri'
        | 'alci-duvar-uygulamalari'
        | 'ytong-tugla-duvar'
        | 'alci-isleri'
        | 'ic-mekan-boyama'
        | 'elektrik-ariza-onarimi'
        | 'dimmer-anahtar-montaji'
        | 'spot-montaji'
        | 'led-aydinlatma-sistemleri'
        | 'elektrik-sayaci-montaji'
        | 'salter-montaj-ve-degisimi'
        | 'jenerator-baglantisi'
        | 'zayif-akim-tesisati'
        | 'kablo-kanali-doseme'
        | 'topraklama-hatti-cekimi'
        | 'elektrik-tesisati-yenileme'
        | 'kacak-akim-rolesi-montaji'
        | 'aydinlatma-tesisati'
        | 'sensor-montaji'
        | 'avize-montaji'
        | 'priz-ve-anahtar-degisimi'
        | 'sigorta-kutusu-yenileme'
        | 'tesisat-kablolari-yenileme'
        | 'elektrik-panosu-yenileme'
        | 'elektrik-ariza-tespiti'
        | 'tesisat-izolasyonu'
        | 'sicak-su-sistemi-kurulumu'
        | 'otomasyon-sistemi-kurulumu'
        | 'gaz-kacagi-tespiti-ve-onarimi'
        | 'isi-istasyonu-kurulum-ve-bakimi'
        | 'kalorifer-tesisati-yenileme'
        | 'isi-pompasi-montaj-ve-bakimi'
        | 'brulor-bakim-ve-tamiri'
        | 'havalandirma-sistemi-kurulumu'
        | 'fancoil-sistem-montaj-ve-bakimi'
        | 'vrf-vrv-sistem-kurulumu'
        | 'termostatik-vana-montaji'
        | 'radyator-montaj-ve-degisimi'
        | 'dogalgaz-tesisat-doseme-ve-bakimi'
        | 'kazan-dairesi-bakim-ve-onarimi'
        | 'yerden-isitma-sistem-kurulumu'
        | 'cift-yonlu-ilacli-petek-temizligi'
        | 'klima-montaj-sokum-ve-bakimi'
        | 'kombi-montaj-tamir-ve-bakimi'
        | 'merkezi-kalorifer-sistemi-kurulumu-ve-bakimi'
        | 'basinc-testi-ve-kontrol'
        | 'termal-kamera-ile-kacak-tespiti'
        | 'rogar-ve-kanal-temizligi'
        | 'yagmur-suyu-drenaji'
        | 'dusakabin-kurulumu'
        | 'lavabo-ve-klozet-montaji'
        | 'musluk-ve-batarya-montaji'
        | 'pis-su-tesisati-doseme'
        | 'pompa-sistemleri-kurulumu'
        | 'su-deposu-bakim-ve-temizligi'
        | 'pprc-boru-tesisati'
        | 'temiz-su-tesisati-doseme'
        | 'tesisat-yenileme-ve-tadilat'
        | 'tikaniklik-acma-hizmeti'
        | 'pis-su-gider-acma'
        | 'su-kacagi-tespiti-ve-tamiri'
        | 'drenaj-hatti-ve-kuyusu-yapimi'
        | 'su-aritma-ve-yumusatma-sistemleri'
        | 'su-sayaclari-kollektor-tesisati'
        | 'hidrofor-tesisati-kurulumu'
        | 'jet-sistemi-montaj-ve-tamiri'
        | 'su-seviye-kontrolu-ve-ayari'
        | 'havuz-kimyasallari-tedariki'
        | 'havuz-firca-ve-supurge-sistemleri'
        | 'kis-bakimi-ve-koruma'
        | 'havuz-tesisat-yenileme'
        | 'havuz-motoru-bakim-ve-tamiri'
        | 'ph-dengeleme-sistemi-kurulumu'
        | 'klor-jeneratoru-montaji'
        | 'skimmer-ve-suzgec-degisimi'
        | 'havuz-kaplama-ve-izolasyonu'
        | 'uv-sterilizasyon-sistemi-montaji'
        | 'havuz-robotu-tamiri'
        | 'havuz-isitma-sistemi-kurulumu'
        | 'havuz-aydinlatma-sistemi-montaji'
        | 'otomatik-dozajlama-sistemi-kurulumu'
        | 'havuz-filtre-sistemi-bakimi'
        | 'havuz-pompasi-montaj-ve-tamiri'
        | 'havuz-suyu-analizi-ve-ilaclama'
        | 'havuz-bakimi-ve-temizligi'
      )
    | null;
  description?: string | null;
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-block';
          }
        | {
            heading?: string | null;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            values?:
              | {
                  title?: string | null;
                  description?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  icon?:
                    | (
                        | '7-24-hizmet'
                        | 'sertifikali-usta'
                        | 'profesyonel-uzmanlik'
                        | 'seffaf-fiyatlandirma'
                        | 'iscilik-ve-malzeme-garantisi'
                        | '25-yillik-tecrube'
                        | 'memnuniyet-garantisi'
                        | 'email'
                        | 'phone'
                        | 'address'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid-section-block';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            variant?: ('subtle' | 'light' | 'dark' | 'primary') | null;
            faqs?:
              | {
                  question?: string | null;
                  answer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select testimonials to display in this section.
             */
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials-block';
          }
        | {
            title?: string | null;
            description?: string | null;
            features?:
              | {
                  feature?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  /**
                   * Detay görseli yükleyin.
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'service-description-block';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Recommended: 404x660px
   */
  featured_image?: (number | null) | Media;
  related_category?: (number | null) | ServiceCategory;
  related_projects?: (number | Project)[] | null;
  related_testimonials?: (number | Testimonial)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name?: string | null;
  profession?: string | null;
  photo?: (number | null) | Media;
  content?: string | null;
  source?: ('manual' | 'google') | null;
  rating?: number | null;
  /**
   * Link to the verified Google review
   */
  reviewUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  slug?: string | null;
  title?: string | null;
  description?: string | null;
  icon?:
    | (
        | 'isitma-ve-sogutma'
        | 'elektrik-tesisat'
        | 'elektronik-tesisat'
        | 'sihhi-tesisat'
        | 'cati-ve-cephe'
        | 'yapi-insaati'
        | 'havuz-sistemleri'
      )
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Recommended: 404x660px
   */
  featured_image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug?: string | null;
  title?: string | null;
  description?: string | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  before_image?: (number | null) | Media;
  after_image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * Form fields
   */
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Recommended: 404x660px
   */
  featured_image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  post_category?: (number | null) | PostCategory;
  related_service_category?: (number | null) | ServiceCategory;
  author?: (number | null) | Author;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  slug?: string | null;
  title?: string | null;
  description?: string | null;
  featured_image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name?: string | null;
  email?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Recommended: 404x660px
   */
  photo?: (number | null) | Media;
  title?: string | null;
  social?: {
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
  };
  status?: ('active' | 'inactive') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  slug?: string | null;
  title: string;
  /**
   * Year or date the certification was issued
   */
  date?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Upload the certificate image (recommended: at least 800x1000px)
   */
  image: number | Media;
  /**
   * Optional: Upload the certificate as PDF for download
   */
  pdf?: (number | null) | Media;
  /**
   * Show this certificate prominently
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-comments".
 */
export interface BlogComment {
  id: number;
  post?: (number | null) | Post;
  /**
   * If this is a reply to another comment
   */
  parent?: (number | null) | BlogComment;
  commenterName?: string | null;
  commenterEmail?: string | null;
  content?: string | null;
  status?: ('pending' | 'approved' | 'spam' | 'rejected') | null;
  /**
   * Internal notes for moderation (not visible to public)
   */
  moderationNotes?: string | null;
  /**
   * Whether the commenter has been notified about the status
   */
  isNotified?: boolean | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: number;
  proposalNumber: string;
  proposalType?: ('proforma' | 'teklif' | 'siparis') | null;
  proposalDate?: string | null;
  status?: ('draft' | 'submitted' | 'accepted' | 'rejected') | null;
  discountPercent?: number | null;
  discountType?: ('percent' | 'amount') | null;
  discountValue?: number | null;
  taxPercent?: number | null;
  pageEndSpacing?: number | null;
  shareToken?: string | null;
  shareTokenExpiry?: string | null;
  discountAmount?: number | null;
  taxAmount?: number | null;
  grandTotal?: number | null;
  customerName?: string | null;
  customerAddress?: string | null;
  customerTaxOffice?: string | null;
  customerTaxNumber?: string | null;
  customerEmail?: string | null;
  customerApprovalName?: string | null;
  subject?: string | null;
  items?:
    | {
        description?: string | null;
        quantity?: string | null;
        unitPrice?: string | null;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  companySnapshot?: {
    companyName?: string | null;
    companySubtitle?: string | null;
    companyAddress?: string | null;
    companyPhone?: string | null;
    companyEmail?: string | null;
    companyTaxOffice?: string | null;
    companyTaxNumber?: string | null;
    validity?: string | null;
    payment?: string | null;
    paymentMethod?: string | null;
    bankName?: string | null;
    bankAccount?: string | null;
    generalTerms?: string | null;
    warrantyTerms?: string | null;
    contractorName?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'blog-comments';
        value: number | BlogComment;
      } | null)
    | ({
        relationTo: 'proposals';
        value: number | Proposal;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  featured_image?: T;
  blocks?:
    | T
    | {
        'home-hero-section'?:
          | T
          | {
              blockType?: T;
              headingRotation?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              subHeading?: T;
              description?: T;
              featuredServices?: T;
              servicesLink?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              images?:
                | T
                | {
                    mainImage?: T;
                    secondaryImage?: T;
                  };
              cta_form?: T;
              id?: T;
              blockName?: T;
            };
        'services-carousel'?:
          | T
          | {
              blockType?: T;
              heading?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                  };
              viewAllLink?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              services?: T;
              id?: T;
              blockName?: T;
            };
        'about-section'?:
          | T
          | {
              blockType?: T;
              certificateSource?: T;
              content?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                    description?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          url?: T;
                        };
                  };
              certificates?:
                | T
                | {
                    title?: T;
                    image?: T;
                    id?: T;
                  };
              collectionOptions?:
                | T
                | {
                    limit?: T;
                    featuredOnly?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-choose-us'?:
          | T
          | {
              blockType?: T;
              image?: T;
              content?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                    description?: T;
                  };
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'work-process'?:
          | T
          | {
              blockType?: T;
              header?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                  };
              description?: T;
              processSteps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    steps?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'portfolio-section'?:
          | T
          | {
              blockType?: T;
              header?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                  };
              description?: T;
              featuredProjects?: T;
              id?: T;
              blockName?: T;
            };
        'testimonials-section'?:
          | T
          | {
              blockType?: T;
              header?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                    description?: T;
                  };
              viewAllButton?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              featuredTestimonials?: T;
              id?: T;
              blockName?: T;
            };
        'blog-section'?:
          | T
          | {
              blockType?: T;
              header?:
                | T
                | {
                    subtitle?: T;
                    title?: T;
                  };
              featuredPosts?: T;
              id?: T;
              blockName?: T;
            };
        'page-hero-block'?:
          | T
          | {
              impact?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        'cta-block'?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'grid-section-block'?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    content?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'certifications-block'?:
          | T
          | {
              certificateSource?: T;
              title?: T;
              description?: T;
              certificates?:
                | T
                | {
                    title?: T;
                    date?: T;
                    image?: T;
                    description?: T;
                    pdfUrl?: T;
                    id?: T;
                  };
              collectionOptions?:
                | T
                | {
                    limit?: T;
                    featuredOnly?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-gallery-block'?:
          | T
          | {
              title?: T;
              description?: T;
              showTitle?: T;
              showCategories?: T;
              images?:
                | T
                | {
                    src?: T;
                    category?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'faq-block'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              variant?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text-block'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'projects-block'?:
          | T
          | {
              title?: T;
              description?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        'testimonials-block'?:
          | T
          | {
              title?: T;
              description?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  featured?: T;
  title?: T;
  icon?: T;
  description?: T;
  blocks?:
    | T
    | {
        'rich-text-block'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'cta-block'?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'grid-section-block'?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    content?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'faq-block'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              variant?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'testimonials-block'?:
          | T
          | {
              title?: T;
              description?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        'service-description-block'?:
          | T
          | {
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured_image?: T;
  related_category?: T;
  related_projects?: T;
  related_testimonials?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon?: T;
  content?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  solution?: T;
  before_image?: T;
  after_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  profession?: T;
  photo?: T;
  content?: T;
  source?: T;
  rating?: T;
  reviewUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  date?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  image?: T;
  pdf?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured_image?: T;
  content?: T;
  post_category?: T;
  related_service_category?: T;
  author?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  bio?: T;
  photo?: T;
  title?: T;
  social?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
      };
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-comments_select".
 */
export interface BlogCommentsSelect<T extends boolean = true> {
  post?: T;
  parent?: T;
  commenterName?: T;
  commenterEmail?: T;
  content?: T;
  status?: T;
  moderationNotes?: T;
  isNotified?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  proposalNumber?: T;
  proposalType?: T;
  proposalDate?: T;
  status?: T;
  discountPercent?: T;
  discountType?: T;
  discountValue?: T;
  taxPercent?: T;
  pageEndSpacing?: T;
  shareToken?: T;
  shareTokenExpiry?: T;
  discountAmount?: T;
  taxAmount?: T;
  grandTotal?: T;
  customerName?: T;
  customerAddress?: T;
  customerTaxOffice?: T;
  customerTaxNumber?: T;
  customerEmail?: T;
  customerApprovalName?: T;
  subject?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        total?: T;
        id?: T;
      };
  note?: T;
  companySnapshot?:
    | T
    | {
        companyName?: T;
        companySubtitle?: T;
        companyAddress?: T;
        companyPhone?: T;
        companyEmail?: T;
        companyTaxOffice?: T;
        companyTaxNumber?: T;
        validity?: T;
        payment?: T;
        paymentMethod?: T;
        bankName?: T;
        bankAccount?: T;
        generalTerms?: T;
        warrantyTerms?: T;
        contractorName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  company_description?: string | null;
  logo?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    secondaryPhone?: string | null;
    whatsapp?: string | null;
    address?: string | null;
    googleMapsUrl?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  /**
   * Select pages to show in main navigation
   */
  mainNavigation?: (number | Page)[] | null;
  /**
   * Select services to show in footer
   */
  footerServices?:
    | (
        | {
            relationTo: 'services';
            value: number | Service;
          }
        | {
            relationTo: 'service-categories';
            value: number | ServiceCategory;
          }
      )[]
    | null;
  /**
   * Select pages to show in footer
   */
  footerLinks?: (number | Page)[] | null;
  copyright?: string | null;
  /**
   * Select legal pages (privacy policy, terms of use, etc.)
   */
  legalPages?: (number | Page)[] | null;
  /**
   * These values are pre-filled when creating new proposals.
   */
  proposalDefaults?: {
    companyName?: string | null;
    companySubtitle?: string | null;
    companyAddress?: string | null;
    companyPhone?: string | null;
    companyEmail?: string | null;
    companyTaxOffice?: string | null;
    companyTaxNumber?: string | null;
    validity?: string | null;
    payment?: string | null;
    paymentMethod?: string | null;
    bankName?: string | null;
    bankAccount?: string | null;
    generalTerms?: string | null;
    warrantyTerms?: string | null;
    contractorName?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  company_description?: T;
  logo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        secondaryPhone?: T;
        whatsapp?: T;
        address?: T;
        googleMapsUrl?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  mainNavigation?: T;
  footerServices?: T;
  footerLinks?: T;
  copyright?: T;
  legalPages?: T;
  proposalDefaults?:
    | T
    | {
        companyName?: T;
        companySubtitle?: T;
        companyAddress?: T;
        companyPhone?: T;
        companyEmail?: T;
        companyTaxOffice?: T;
        companyTaxNumber?: T;
        validity?: T;
        payment?: T;
        paymentMethod?: T;
        bankName?: T;
        bankAccount?: T;
        generalTerms?: T;
        warrantyTerms?: T;
        contractorName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'pages'
      | 'services'
      | 'service-categories'
      | 'projects'
      | 'testimonials'
      | 'certifications'
      | 'posts'
      | 'post-categories'
      | 'authors'
      | 'blog-comments'
      | 'proposals'
      | 'users'
      | 'media'
      | 'forms'
      | 'form-submissions'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}